### ISSUE TITLE
Audio in-ear (request)

### ISSUE THREAD

**Issue by albertopasqualetto** [lodauria/AudioSpeedUp#1]
If the phone (proximity sensor) is near the ear, the audio should be played trough the phone capsule.
(Really good job)

**Comment by ghost** [comment]
Nice idea!
I will try to add this feature in future releases.

**Comment by ghost** [comment]
Added in the last release!

**Comment by albertopasqualetto** [comment]
The proximity sensor works only if opening the app (for example clicking on the notification).

**Comment by ghost** [comment]
Of course, Android doesn't allow to detect proximity if the app is in background.

**Comment by albertopasqualetto** [comment]
Is it possibile to make the app as a transparent overlay while it is reproducing the voice note so that the proximity can be detected but the smartphone is still usable? The app "Quick Settings" can deviate all the device's audio to the phone capsule.

**Comment by ghost** [comment]
The app can be made transparent, but while the app is on focus with the transparent window (and the proximity sensor detected) the other apps can't be used even if they are normally visible.
The problem is not reproducing the audio in the in phone capsule when the app is in background, the problem is detecting proximity, because this is done by a particular thread which is interrupted by Android when the app is not on focus.
I think that, since when you listen to the audio with the in ear speaker you don't need to use other apps on the phone, tapping on the notification and then put the phone near your ear is a good compromise.

**Comment by albertopasqualetto** [comment]
Ok, you are right, in any case if in the future there will be the possibility to do it in a quicker way it will be a good thing.
Good job
