### ISSUE TITLE
The stop button behaves weirdly 

### ISSUE THREAD

**Issue by nocturn9x** [lodauria/AudioSpeedUp#25]
The right button on the main UI has a weird behavior, that icon is generally meant to stop the playback, but it will just restart it from the beginning (and reset the play icon as if the audio was paused)

My device is Honor 9 lite with EMUI 9.0.1

**Comment by ghost** [comment]
This app was thought to work only with an audio file selected, so stopping the playback would mean closing the app, don't you think this behavior would be worst? The app already shuts down when is not on focus and the stop button on the notification is clicked. If someone, after sharing a file and listening to it, puts the app on focus is because wants to change some of the parameters on the main screen, when finished he can switch to an other app or simply close the application without the needing of clicking the stop button for closing the app.

**Comment by nocturn9x** [comment]
Makes sense to me

Il mer 8 apr 2020, 08:31 bonsky97 <notifications@github.com> ha scritto:

**Comment by ghost** [comment]
Ok, I will think about it, thanks for the report.
